# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HardWareInfo',
            fields=[
                ('ip', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('system', models.CharField(max_length=15)),
                ('memory', models.CharField(max_length=15)),
                ('disk', models.CharField(max_length=15)),
                ('cpu', models.IntegerField()),
                ('contractor', models.CharField(max_length=15)),
                ('price', models.IntegerField()),
                ('comments', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('ip', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('port', models.IntegerField(default=22)),
                ('group', models.CharField(choices=[('\u751f\u4ea7', '\u751f\u4ea7'), ('\u6d4b\u8bd5', '\u6d4b\u8bd5')], max_length=8)),
                ('user', models.CharField(max_length=10)),
                ('pwd', models.CharField(max_length=10)),
                ('login_type', models.CharField(choices=[('\u5bc6\u7801\u65b9\u5f0f', '\u5bc6\u7801\u65b9\u5f0f'), ('\u79d8\u94a5\u65b9\u5f0f', '\u79d8\u94a5\u65b9\u5f0f')], max_length=10)),
                ('sudo', models.CharField(blank=True, max_length=10, null=True)),
                ('us_sudo', models.CharField(choices=[('\u5426', '\u5426'), ('\u662f', '\u662f')], max_length=10)),
                ('us_su', models.CharField(choices=[('\u5426', '\u5426'), ('\u662f', '\u662f')], max_length=10)),
                ('key', models.FileField(blank=True, null=True, upload_to='keys')),
                ('alive', models.IntegerField(choices=[(0, 'dead'), (1, 'alive')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PushCodeEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=30)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-ctime'],
            },
        ),
        migrations.CreateModel(
            name='TopContServer',
            fields=[
                ('ip', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('uptime', models.DateTimeField(auto_now=True)),
                ('acount', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['-acount'],
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('pwd', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=32)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('uptime', models.DateTimeField(auto_now=True)),
                ('user_type', models.CharField(choices=[('user', 'user'), ('admin', 'admin')], max_length=10)),
                ('group', models.CharField(choices=[('user', 'user'), ('admin', 'admin')], max_length=10, null=True)),
                ('hdimg', models.FileField(blank=True, null=True, upload_to='static/img/head/')),
                ('alive', models.IntegerField(choices=[(0, 'dead'), (1, 'alive')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserLock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ip', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.CharField(max_length=20)),
                ('status', models.IntegerField(default=1)),
                ('uptime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='usergroup',
            name='group_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.UserInfo'),
        ),
        migrations.AddField(
            model_name='topcontserver',
            name='user_id',
            field=models.ManyToManyField(to='ops.UserInfo'),
        ),
        migrations.AddField(
            model_name='pushcodeevent',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.UserInfo'),
        ),
        migrations.AddField(
            model_name='hostgroup',
            name='group_name',
            field=models.ForeignKey(max_length=16, null=True, on_delete=django.db.models.deletion.CASCADE, to='ops.HostInfo'),
        ),
    ]
