# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-05 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-update_time']},
        ),
    ]
