# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0002_hostinfo_su'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostinfo',
            name='bz',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
