# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-08 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0002_auto_20171105_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ansible_Model_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_user', models.CharField(default=None, max_length=50, verbose_name='\u4f7f\u7528\u7528\u6237')),
                ('ans_model', models.CharField(default=None, max_length=100, verbose_name='\u6a21\u5757\u540d\u79f0')),
                ('ans_args', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='\u6a21\u5757\u53c2\u6570')),
                ('ans_server', models.TextField(default=None, verbose_name='\u670d\u52a1\u5668')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u6267\u884c\u65f6\u95f4')),
            ],
            options={
                'db_table': 'log_ansible_model',
                'verbose_name': 'Ansible\u6a21\u5757\u6267\u884c\u8bb0\u5f55\u8868',
                'verbose_name_plural': 'Ansible\u6a21\u5757\u6267\u884c\u8bb0\u5f55\u8868',
                'permissions': (('can_read_log_ansible_model', '\u8bfb\u53d6Ansible\u6a21\u5757\u6267\u884c\u8bb0\u5f55\u6743\u9650'), ('can_change_log_ansible_model', '\u66f4\u6539Ansible\u6a21\u5757\u6267\u884c\u8bb0\u5f55\u6743\u9650'), ('can_add_log_ansible_model', '\u6dfb\u52a0Ansible\u6a21\u5757\u6267\u884c\u8bb0\u5f55\u6743\u9650'), ('can_delete_log_ansible_model', '\u5220\u9664Ansible\u6a21\u5757\u6267\u884c\u8bb0\u5f55\u6743\u9650')),
            },
        ),
    ]
