# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0003_hostinfo_bz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'ordering': ['-uptime']},
        ),
    ]
