# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-08 01:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0003_ansible_model_log'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ansible_model_log',
            table=None,
        ),
    ]
