# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0003_hostinfo_bz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='group',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='us_su',
            field=models.CharField(choices=[('N', 'N'), ('Y', 'Y')], max_length=10),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='us_sudo',
            field=models.CharField(choices=[('N', 'N'), ('Y', 'Y')], max_length=10),
        ),
    ]
