# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0003_hostinfo_bz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='group',
            field=models.CharField(max_length=15),
        ),
    ]
