# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-08 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0006_ansible_playbook_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Global_Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ansible_model', models.SmallIntegerField(blank=True, null=True, verbose_name='\u662f\u5426\u5f00\u542fansible\u6a21\u5757\u64cd\u4f5c\u8bb0\u5f55')),
                ('ansible_playbook', models.SmallIntegerField(blank=True, null=True, verbose_name='\u662f\u5426\u5f00\u542fansible\u5267\u672c\u64cd\u4f5c\u8bb0\u5f55')),
                ('cron', models.SmallIntegerField(blank=True, null=True, verbose_name='\u662f\u5426\u5f00\u542f\u8ba1\u5212\u4efb\u52a1\u64cd\u4f5c\u8bb0\u5f55')),
                ('project', models.SmallIntegerField(blank=True, null=True, verbose_name='\u662f\u5426\u5f00\u542f\u9879\u76ee\u64cd\u4f5c\u8bb0\u5f55')),
                ('assets', models.SmallIntegerField(blank=True, null=True, verbose_name='\u662f\u5426\u5f00\u542f\u8d44\u4ea7\u64cd\u4f5c\u8bb0\u5f55')),
                ('server', models.SmallIntegerField(blank=True, null=True, verbose_name='\u662f\u5426\u5f00\u542f\u670d\u52a1\u5668\u547d\u4ee4\u8bb0\u5f55')),
                ('email', models.SmallIntegerField(blank=True, null=True, verbose_name='\u662f\u5426\u5f00\u542f\u90ae\u4ef6\u901a\u77e5')),
            ],
        ),
    ]
