# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-08 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0007_global_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ansible_playbook',
            name='playbook_auth_group',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u6388\u6743\u7ec4'),
        ),
        migrations.AlterField(
            model_name='ansible_playbook',
            name='playbook_auth_user',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u6388\u6743\u7528\u6237'),
        ),
    ]
