# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-13 11:08
from __future__ import unicode_literals

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('ops', '0009_auto_20171108_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissonList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u6743\u9650\u540d\u79f0')),
                ('url', models.CharField(max_length=255, verbose_name='URL\u5730\u5740')),
            ],
        ),
        migrations.CreateModel(
            name='RoleList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u90e8\u95e8\u540d\u79f0')),
                ('permission', models.ManyToManyField(blank=True, to='ops.PermissonList', verbose_name='\u6743\u9650')),
            ],
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='group_name',
        ),
        migrations.AlterModelOptions(
            name='ansible_playbook_number',
            options={'permissions': (('can_read_ansible_playbook_number', '\u8bfb\u53d6Ansible\u5267\u672c\u6210\u5458\u6743\u9650'), ('can_change_ansible_playbook_number', '\u66f4\u6539Ansible\u5267\u672c\u6210\u5458\u6743\u9650'), ('can_add_ansible_playbook_number', '\u6dfb\u52a0Ansible\u5267\u672c\u6210\u5458\u6743\u9650'), ('can_delete_ansible_playbook_number', '\u5220\u9664Ansible\u5267\u672c\u6210\u5458\u6743\u9650'), ('can_do_all_ansible_playbook_number', '\u6240\u6709Ansible\u5267\u672c\u6210\u5458/\u6743\u9650')), 'verbose_name': 'Ansible\u5267\u672c\u6210\u5458\u8868', 'verbose_name_plural': 'Ansible\u5267\u672c\u6210\u5458\u8868'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='userinfo',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='alive',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='ctime',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='group',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='hdimg',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='pwd',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='uptime',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user_type',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='birthday',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='\u751f\u65e5'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='fullname',
            field=models.CharField(default=None, max_length=64, null=True, unique=True, verbose_name='\u59d3\u540d'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='password',
            field=models.CharField(default='a', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='sex',
            field=models.CharField(max_length=2, null=True, verbose_name='\u6027\u522b'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='username',
            field=models.CharField(default='a', error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.DeleteModel(
            name='UserGroup',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='permission',
            field=models.ManyToManyField(blank=True, to='ops.PermissonList', verbose_name='\u6743\u9650'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ops.RoleList', verbose_name='\u90e8\u95e8'),
        ),
    ]
