# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-13 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0010_auto_20171113_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='head_img',
            field=models.FileField(default='a', upload_to='user/', verbose_name='\u7528\u6237\u5934\u50cf'),
            preserve_default=False,
        ),
    ]
