# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-13 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0011_userinfo_head_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='pub_key',
            field=models.TextField(default='aaaa', max_length=500, verbose_name='\u516c\u94a5'),
            preserve_default=False,
        ),
    ]
