# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-13 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0012_userinfo_pub_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assets_type', models.CharField(choices=[('server', '\u670d\u52a1\u5668'), ('switch', '\u4ea4\u6362\u673a'), ('route', '\u8def\u7531\u5668'), ('printer', '\u6253\u5370\u673a'), ('scanner', '\u626b\u63cf\u4eea'), ('firewall', '\u9632\u706b\u5899'), ('storage', '\u5b58\u50a8\u8bbe\u5907'), ('wifi', '\u65e0\u7ebf\u8bbe\u5907')], default='server', max_length=100, verbose_name='\u8d44\u4ea7\u7c7b\u578b')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='\u8d44\u4ea7\u7f16\u53f7')),
                ('sn', models.CharField(max_length=100, verbose_name='\u8bbe\u5907\u5e8f\u5217\u53f7')),
                ('buy_time', models.DateField(blank=True, null=True, verbose_name='\u8d2d\u4e70\u65f6\u95f4')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='\u8fc7\u4fdd\u4fee\u671f')),
                ('buy_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8d2d\u4e70\u4eba')),
                ('management_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='\u7ba1\u7406IP')),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5236\u9020\u5546')),
                ('provider', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u4f9b\u8d27\u5546')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8d44\u4ea7\u578b\u53f7')),
                ('status', models.SmallIntegerField(blank=True, null=True, verbose_name='\u72b6\u6001')),
                ('put_zone', models.SmallIntegerField(blank=True, null=True, verbose_name='\u653e\u7f6e\u533a\u57df')),
                ('group', models.SmallIntegerField(blank=True, null=True, verbose_name='\u4f7f\u7528\u7ec4')),
                ('business', models.SmallIntegerField(blank=True, null=True, verbose_name='\u4e1a\u52a1\u7c7b\u578b')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Business_Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100, verbose_name='\u4e1a\u52a1\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='Disk_Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_volume', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u786c\u76d8\u5bb9\u91cf')),
                ('device_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u786c\u76d8\u72b6\u6001')),
                ('device_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u786c\u76d8\u578b\u53f7')),
                ('device_brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u786c\u76d8\u751f\u4ea7\u5546')),
                ('device_serial', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u786c\u76d8\u5e8f\u5217\u53f7')),
                ('device_slot', models.SmallIntegerField(blank=True, null=True, verbose_name='\u786c\u76d8\u63d2\u69fd')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('assets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.Assets')),
            ],
            options={
                'verbose_name': '\u78c1\u76d8\u8d44\u4ea7\u8868',
                'verbose_name_plural': '\u78c1\u76d8\u8d44\u4ea7\u8868',
                'permissions': (('can_read_disk_assets', '\u8bfb\u53d6\u78c1\u76d8\u8d44\u4ea7\u6743\u9650'), ('can_change_disk_assets', '\u66f4\u6539\u78c1\u76d8\u8d44\u4ea7\u6743\u9650'), ('can_add_disk_assets', '\u6dfb\u52a0\u78c1\u76d8\u8d44\u4ea7\u6743\u9650'), ('can_delete_disk_assets', '\u5220\u9664\u78c1\u76d8\u8d44\u4ea7\u6743\u9650')),
            },
        ),
        migrations.CreateModel(
            name='Idc_Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='\u673a\u623f\u540d\u79f0')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='\u673a\u623f\u5730\u5740')),
                ('tel', models.CharField(max_length=30, null=True, verbose_name='\u673a\u623f\u7535\u8bdd')),
                ('contact', models.CharField(max_length=30, null=True, verbose_name='\u5ba2\u6237\u7ecf\u7406')),
                ('contact_phone', models.CharField(max_length=30, null=True, verbose_name='\u79fb\u52a8\u7535\u8bdd')),
                ('jigui', models.CharField(max_length=30, null=True, verbose_name='\u673a\u67dc\u4fe1\u606f')),
                ('ip_range', models.CharField(max_length=30, null=True, verbose_name='IP\u8303\u56f4')),
                ('bandwidth', models.CharField(max_length=30, null=True, verbose_name='\u63a5\u5165\u5e26\u5bbd')),
            ],
            options={
                'verbose_name': '\u6570\u636e\u4e2d\u5fc3',
                'verbose_name_plural': '\u6570\u636e\u4e2d\u5fc3',
            },
        ),
        migrations.CreateModel(
            name='Line_Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'opman_line_assets',
                'verbose_name': '\u51fa\u53e3\u7ebf\u8def\u8d44\u4ea7\u8868',
                'verbose_name_plural': '\u51fa\u53e3\u7ebf\u8def\u8d44\u4ea7\u8868',
                'permissions': (('can_read_line_assets', '\u8bfb\u53d6\u51fa\u53e3\u7ebf\u8def\u8d44\u4ea7\u6743\u9650'), ('can_change_line_assetss', '\u66f4\u6539\u51fa\u53e3\u7ebf\u8def\u8d44\u4ea7\u6743\u9650'), ('can_add_line_assets', '\u6dfb\u52a0\u51fa\u53e3\u7ebf\u8def\u8d44\u4ea7\u6743\u9650'), ('can_delete_line_assets', '\u5220\u9664\u51fa\u53e3\u7ebf\u8def\u8d44\u4ea7\u6743\u9650')),
            },
        ),
        migrations.CreateModel(
            name='Network_Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandwidth', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u80cc\u677f\u5e26\u5bbd')),
                ('ip', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u7ba1\u7406ip')),
                ('port_number', models.SmallIntegerField(blank=True, null=True, verbose_name='\u7aef\u53e3\u4e2a\u6570')),
                ('firmware', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u56fa\u4ef6\u7248\u672c')),
                ('cpu', models.CharField(blank=True, max_length=100, null=True, verbose_name='cpu\u578b\u53f7')),
                ('stone', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5185\u5b58\u5927\u5c0f')),
                ('configure_detail', models.TextField(blank=True, max_length=100, null=True, verbose_name='\u914d\u7f6e\u8bf4\u660e')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('assets', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ops.Assets')),
            ],
            options={
                'verbose_name': '\u7f51\u7edc\u8d44\u4ea7\u8868',
                'verbose_name_plural': '\u7f51\u7edc\u8d44\u4ea7\u8868',
                'permissions': (('can_read_network_assets', '\u8bfb\u53d6\u7f51\u7edc\u8d44\u4ea7\u6743\u9650'), ('can_change_network_assets', '\u66f4\u6539\u7f51\u7edc\u8d44\u4ea7\u6743\u9650'), ('can_add_network_assets', '\u6dfb\u52a0\u7f51\u7edc\u8d44\u4ea7\u6743\u9650'), ('can_delete_network_assets', '\u5220\u9664\u7f51\u7edc\u8d44\u4ea7\u6743\u9650')),
            },
        ),
        migrations.CreateModel(
            name='Raid_Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raid_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Raid\u8d44\u4ea7\u8868',
                'verbose_name_plural': 'Raid\u8d44\u4ea7\u8868',
                'permissions': (('can_read_raid_assets', '\u8bfb\u53d6Raid\u8d44\u4ea7\u6743\u9650'), ('can_change_raid_assets', '\u66f4\u6539Raid\u8d44\u4ea7\u6743\u9650'), ('can_add_raid_assets', '\u6dfb\u52a0Raid\u8d44\u4ea7\u6743\u9650'), ('can_delete_raid_assets', '\u5220\u9664Raid\u8d44\u4ea7\u6743\u9650')),
            },
        ),
        migrations.CreateModel(
            name='Ram_Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5185\u5b58\u578b\u53f7')),
                ('device_volume', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5185\u5b58\u5bb9\u91cf')),
                ('device_brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5185\u5b58\u751f\u4ea7\u5546')),
                ('device_slot', models.SmallIntegerField(blank=True, null=True, verbose_name='\u5185\u5b58\u63d2\u69fd')),
                ('device_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5185\u5b58\u72b6\u6001')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('assets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.Assets')),
            ],
            options={
                'verbose_name': '\u5185\u5b58\u8d44\u4ea7\u8868',
                'verbose_name_plural': '\u5185\u5b58\u8d44\u4ea7\u8868',
                'permissions': (('can_read_ram_assets', '\u8bfb\u53d6\u5185\u5b58\u8d44\u4ea7\u6743\u9650'), ('can_change_ram_assets', '\u66f4\u6539\u5185\u5b58\u8d44\u4ea7\u6743\u9650'), ('can_add_ram_assets', '\u6dfb\u52a0\u5185\u5b58\u8d44\u4ea7\u6743\u9650'), ('can_delete_ram_assets', '\u5220\u9664\u5185\u5b58\u8d44\u4ea7\u6743\u9650')),
            },
        ),
        migrations.CreateModel(
            name='Service_Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'opman_service_assets',
                'verbose_name': '\u4e1a\u52a1\u5206\u7ec4\u8868',
                'verbose_name_plural': '\u4e1a\u52a1\u5206\u7ec4\u8868',
                'permissions': (('can_read_service_assets', '\u8bfb\u53d6\u4e1a\u52a1\u8d44\u4ea7\u6743\u9650'), ('can_change_service_assets', '\u66f4\u6539\u4e1a\u52a1\u8d44\u4ea7\u6743\u9650'), ('can_add_service_assets', '\u6dfb\u52a0\u4e1a\u52a1\u8d44\u4ea7\u6743\u9650'), ('can_delete_service_assets', '\u5220\u9664\u4e1a\u52a1\u8d44\u4ea7\u6743\u9650')),
            },
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='head_img',
            field=models.FileField(default='user/img/cd-avatar.png', upload_to='user/img/', verbose_name='\u7528\u6237\u5934\u50cf'),
        ),
        migrations.AlterUniqueTogether(
            name='ram_assets',
            unique_together=set([('assets', 'device_slot')]),
        ),
        migrations.AlterUniqueTogether(
            name='disk_assets',
            unique_together=set([('assets', 'device_slot')]),
        ),
    ]
