# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-13 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0014_log_assets_zone_assets'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='service_assets',
            table=None,
        ),
    ]
