# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-13 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0015_auto_20171113_2212'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='line_assets',
            table=None,
        ),
        migrations.AlterModelTable(
            name='log_assets',
            table=None,
        ),
        migrations.AlterModelTable(
            name='zone_assets',
            table=None,
        ),
    ]
