# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-14 17:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0016_auto_20171113_2220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostinfo',
            options={'permissions': (('can_read_server_assets', '\u8bfb\u53d6\u670d\u52a1\u5668\u8d44\u4ea7\u6743\u9650'), ('can_change_server_assets', '\u66f4\u6539\u670d\u52a1\u5668\u8d44\u4ea7\u6743\u9650'), ('can_add_server_assets', '\u6dfb\u52a0\u670d\u52a1\u5668\u8d44\u4ea7\u6743\u9650'), ('can_delete_server_assets', '\u5220\u9664\u670d\u52a1\u5668\u8d44\u4ea7\u6743\u9650')), 'verbose_name': '\u670d\u52a1\u5668\u8d44\u4ea7\u8868', 'verbose_name_plural': '\u670d\u52a1\u5668\u8d44\u4ea7\u8868'},
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='assets',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='ops.Assets'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='cpu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='cpu_core',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='cpu_number',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 14, 17, 0, 21, 744345)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='disk_total',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='hostname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='kernel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='line',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='raid',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='ram_total',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='selinux',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='swap',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='system',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 14, 17, 0, 25, 981934)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='vcpu_number',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='hostinfo',
            unique_together=set([]),
        ),
    ]
