# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-14 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0017_auto_20171114_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostinfo',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='ip',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
