# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-14 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0019_auto_20171114_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='key',
            field=models.FileField(blank=True, default='N', null=True, upload_to='keys'),
        ),
    ]
