# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-14 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0020_auto_20171114_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='pwd',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
