# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-14 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0023_auto_20171114_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='ip',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
