# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-14 23:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0024_assets_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='ip',
        ),
    ]
