# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-15 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0025_remove_assets_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='group',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='ip',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='login_type',
            field=models.CharField(choices=[('\u5bc6\u7801\u65b9\u5f0f', '\u5bc6\u7801\u65b9\u5f0f'), ('\u79d8\u94a5\u65b9\u5f0f', '\u79d8\u94a5\u65b9\u5f0f')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='port',
            field=models.IntegerField(default=22, null=True),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='user',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
