# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-15 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0026_auto_20171115_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='pwd',
            field=models.CharField(default='N', max_length=10, null=True),
        ),
    ]
