# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-16 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0027_auto_20171115_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='group',
            field=models.CharField(default='default', max_length=15, null=True),
        ),
    ]
